In [1]:
import numpy as np

### numpy vs list

In [2]:
np.array([1,2,3]).dtype

dtype('int32')

In [3]:
np.array([1,2.2,3]).dtype

dtype('float64')

In [4]:
l1 = [1,2,3]
l2 = [1,2.2,3]
l1 , l2

([1, 2, 3], [1, 2.2, 3])

In [5]:
#l1*l2
np.array([1,2,3])*np.array([4,5,6])

array([ 4, 10, 18])

### 2D array

In [6]:
d2 = np.array([ [1,2,3],[4,5,6] ])

In [7]:
d2.ndim  , d2.shape , d2.dtype 

(2, (2, 3), dtype('int32'))

In [8]:
d2.size , d2.itemsize , d2.nbytes

(6, 4, 24)

In [9]:
 d2.sum() , d2.min() , d2.std() , d2.mean() 

(21, 1, 1.707825127659933, 3.5)

In [10]:
d2.min(axis=0) , d2.min(axis=1) 

(array([1, 2, 3]), array([1, 4]))

In [11]:
np.array([ [1,2,3],[4,5,6] ]  , dtype='int8').dtype

dtype('int8')

In [12]:
d2 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
d2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
d2[0:-1,0:-1,] , d2[0:-1,0:3]

(array([[1, 2],
        [4, 5]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [14]:
d2[:,2] , d2[0,:]

(array([3, 6, 9]), array([1, 2, 3]))

### 3D array 

In [15]:
d3 = np.array([ [[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]] ])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
d3.ndim , d3.shape , d3.dtype 

(3, (2, 2, 3), dtype('int32'))

In [17]:
np.array([ [[1,2],[3,4],[5,6]] , [[7,8],[9,10],[11,12]] , [[7,8],[9,10],[11,12]]]).shape

(3, 3, 2)

In [18]:
d3[0,0,2] , d3[1,:,:]

(3,
 array([[ 7,  8,  9],
        [10, 11, 12]]))

### Working with array

In [19]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.zeros((2,3,2)).reshape((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
np.ones((2,2,1,2))

array([[[[1., 1.]],

        [[1., 1.]]],


       [[[1., 1.]],

        [[1., 1.]]]])

In [22]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [23]:
np.random.random(5) #1D

array([0.2251262 , 0.75440538, 0.66369463, 0.08838165, 0.6410603 ])

In [24]:
np.random.rand(2,2) #random float num

array([[0.29631913, 0.51017148],
       [0.54602548, 0.74161194]])

In [25]:
np.random.randint(1,5, (2,2))

array([[2, 3],
       [1, 3]])

In [26]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.repeat(1,4) , np.repeat(d2,2, axis=0)

(array([1, 1, 1, 1]),
 array([[1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9]]))

In [28]:
#exp
o = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
o[1:-1,1:-1]=z
o

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
a = np.array([ [1,2,3],[5,6,7] ])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [30]:
a.reshape(3,2)

array([[1, 2],
       [3, 5],
       [6, 7]])

In [31]:
v1 = np.array([1,2,3])
v2 = np.array([0,3,2])
np.vstack((v1,v2)) #vertical stacking

array([[1, 2, 3],
       [0, 3, 2]])

In [32]:
np.hstack((v1,v2)) #horizontal stacking

array([1, 2, 3, 0, 3, 2])

In [33]:
d2 = np.array( [[1,2,-1],[3,4,-2]] )
d2

array([[ 1,  2, -1],
       [ 3,  4, -2]])

In [34]:
#boolean masking 
d2==3 , d2[d2>=3] 

(array([[False, False, False],
        [ True, False, False]]),
 array([3, 4]))

In [35]:
np.any(d2>3 , axis=0)

array([False,  True, False])

In [36]:
np.any(d2>3)  ,  np.all(d2>3) 

(True, False)

In [37]:
( (d2<2) & (d2>0) )

array([[ True, False, False],
       [False, False, False]])

### Math, Linear algebra, Statistics

In [38]:
a = np.array([1,2,0,4])
b = np.array([1,0,1,2])

In [39]:
a+b , a*b , a/b , a-b , a**b , np.cos(a)

C:\Users\pc\AppData\Local\Temp\ipykernel_10204\2211108670.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a+b , a*b , a/b , a-b , a**b , np.cos(a)


(array([2, 2, 1, 6]),
 array([1, 0, 0, 8]),
 array([ 1., inf,  0.,  2.]),
 array([ 0,  2, -1,  2]),
 array([ 1,  1,  0, 16], dtype=int32),
 array([ 0.54030231, -0.41614684,  1.        , -0.65364362]))

In [40]:
a = np.ones((2,3))
b = np.full((3,2),3)

In [41]:
a , b , np.matmul(a,b) #multiplication matricial

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[3, 3],
        [3, 3],
        [3, 3]]),
 array([[9., 9.],
        [9., 9.]]))

In [42]:
np.linalg.det(np.identity(3))

1.0

In [43]:
s = np.array([ [1,2,3],[4,5,6] ])

In [44]:
s.min() , s.max() , s.sum() , s.size , s.mean() , s.std() , 

(1, 6, 21, 6, 3.5, 1.707825127659933)

#### Load data text from file

In [58]:
np.genfromtxt('.\DataSets\Wladcha3b.csv', delimiter=',')

array([[    nan,     nan,     nan,     nan,     nan],
       [7.0e+00, 2.5e+03, 6.0e+00, 1.0e+00, 1.0e+00],
       [6.0e+00, 2.0e+03, 4.0e+00, 1.0e+00, 1.0e+00],
       [7.0e+00, 2.5e+03, 5.0e+00, 1.0e+00, 1.0e+00],
       [7.0e+00, 2.0e+03, 5.0e+00, 1.0e+00, 1.0e+00],
       [6.0e+00, 1.5e+03, 6.0e+00, 1.0e+00, 1.0e+00],
       [1.0e+01, 1.0e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [1.1e+01, 1.2e+04, 2.0e+00, 0.0e+00, 0.0e+00],
       [1.2e+01, 1.0e+04, 0.0e+00, 0.0e+00, 0.0e+00],
       [1.2e+01, 1.1e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [1.1e+01, 1.3e+04, 0.0e+00, 0.0e+00, 0.0e+00],
       [1.1e+01, 1.2e+04, 2.0e+00, 0.0e+00, 0.0e+00],
       [1.2e+01, 1.0e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [1.2e+01, 1.3e+04, 0.0e+00, 0.0e+00, 0.0e+00],
       [1.0e+01, 1.4e+04, 0.0e+00, 0.0e+00, 0.0e+00],
       [1.0e+01, 1.1e+04, 1.0e+00, 0.0e+00, 0.0e+00],
       [6.0e+00, 1.5e+03, 6.0e+00, 1.0e+00, 1.0e+00],
       [7.0e+00, 2.0e+03, 5.0e+00, 1.0e+00, 1.0e+00],
       [7.0e+00, 2.5e+03, 4.

In [69]:
np.loadtxt('.\DataSets\Wladcha3b.csv',dtype='string_' , delimiter=',')

array([[b'\xef\xbb\xbflfya9', b'salaire', b'lwlad', b'tkarfis', b'label'],
       [b'7', b'2500', b'6', b'1', b'1'],
       [b'6', b'2000', b'4', b'1', b'1'],
       [b'7', b'2500', b'5', b'1', b'1'],
       [b'7', b'2000', b'5', b'1', b'1'],
       [b'6', b'1500', b'6', b'1', b'1'],
       [b'10', b'10000', b'1', b'0', b'0'],
       [b'11', b'12000', b'2', b'0', b'0'],
       [b'12', b'10000', b'0', b'0', b'0'],
       [b'12', b'11000', b'1', b'0', b'0'],
       [b'11', b'13000', b'0', b'0', b'0'],
       [b'11', b'12000', b'2', b'0', b'0'],
       [b'12', b'10000', b'1', b'0', b'0'],
       [b'12', b'13000', b'0', b'0', b'0'],
       [b'10', b'14000', b'0', b'0', b'0'],
       [b'10', b'11000', b'1', b'0', b'0'],
       [b'6', b'1500', b'6', b'1', b'1'],
       [b'7', b'2000', b'5', b'1', b'1'],
       [b'7', b'2500', b'4', b'1', b'1'],
       [b'6', b'2200', b'5', b'1', b'1']], dtype='|S8')

In [71]:
np.savetxt('wb.txt')

TypeError: _savetxt_dispatcher() missing 1 required positional argument: 'X'